In [ ]:
NUMPY

In [1]:
import numpy as np

In [2]:
#1 dimensional array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
#multidimensional array
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a1.shape

(3, 3)

In [ ]:
a1=np.array([])

In [10]:
#inserting elements into array dynamically
a1.dtype

12


dtype('int32')

In [12]:
a1=np.append(a1,[23,34,45,56,67])
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12, 23, 34, 45, 56, 67])

In [13]:
#slicing
print(a1[3])

4


In [18]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
print(a2[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [20]:
print(a2[2:,0:2])

[[ 7  8]
 [10 11]]


In [22]:
print(a2[0,0:2])

[1 2]


In [23]:
#iterate through array
for row in a2:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [24]:
for ele in a2.flat:  #flattens all attributes of an array
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [25]:
np.array(a2.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
#indexing with boolean array
arr1=np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [28]:
result = (arr1%2 ==0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [29]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
#appending arrays
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [33]:
print(np.vstack((arr1,arr2)))   #vertical stacking of array

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [34]:
print(np.hstack((arr1,arr2)))    #horizontal stacking

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [35]:
#attributes size,itemsize,dtype,ndim,shape

arr=np.arange(1,11).reshape(2,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [36]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


In [ ]:
#functions:   zeros(),ones(),full(),eye(),linspace(),arange(),reshape(),ravel()

In [37]:
z=np.zeros((2,3),dtype="int32")           #default datatype is float
z

array([[0, 0, 0],
       [0, 0, 0]])

In [38]:
o=np.ones((3,3),dtype="int32")
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
f=np.full((2,2),"meghana")
print(f)

[['meghana' 'meghana']
 ['meghana' 'meghana']]


In [42]:
e=np.eye(3,dtype="int32")     #only diagonal elements will be 1 and remaining 0---->identical matrix
e   

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [44]:
#linspace()--->linear spaced array will be returned
l=np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [47]:
a=np.arange(1,13,2) #arange(start,stop,step)
a

array([ 1,  3,  5,  7,  9, 11])

In [51]:
a=a.reshape(2,3)
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [52]:
#ravel
print(np.array(a.flat))
print(a.ravel())

[ 1  3  5  7  9 11]
[ 1  3  5  7  9 11]


In [ ]:
#function:  min(),max(),sum(),sqrt(),mean(),median(),std()

In [53]:
print(a.min())
print(a.max())

1
11


In [56]:
print(a.sum())     #sum of all elements
print(a.sum(axis=1))    #sum of row elements
print(a.sum(axis=0))    #sum of column elements

36
[ 9 27]
[ 8 12 16]


In [61]:
np.sqrt(a)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479]])

In [58]:
np.mean(a)

6.0

In [59]:
np.median(a)

6.0

In [60]:
np.std(a)


3.415650255319866

In [62]:
#mathematical operations
arr1=np.arange(1,11)
arr2=np.arange(11,21)
print(arr1+arr2)
print(arr2-arr1)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)

[12 14 16 18 20 22 24 26 28 30]
[10 10 10 10 10 10 10 10 10 10]
[ 11  24  39  56  75  96 119 144 171 200]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
[ 1  2  3  4  5  6  7  8  9 10]


In [63]:
#dot() --->matrix multiplication  arr1=mXn   arr2=nX1
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [64]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr1.T     #transpose of an array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [68]:
#applying user defined functions on an array
list1=list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [72]:
a=np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [70]:
#1/(1+1)  ---> x/(x+1)
result = [x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [73]:
f=np.vectorize(lambda x: x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])