In [2]:
#numpy random

from numpy import random
print(random.randint(1,100))  #random integer in the given range
print(random.rand())  #float number 0-1

48
0.6411262518014291


In [3]:
#creating n dimensional array with random values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[63 66 75]
[[ 9 81 47 66]
 [ 0 40 83 21]
 [34 11 84 16]]
[[[86  0]
  [85 19]
  [53 90]
  [ 3 71]]

 [[30 46]
  [55 77]
  [20  2]
  [82 83]]

 [[18 30]
  [57 18]
  [88 78]
  [18 34]]]


In [7]:
#creating n dimensional array with random floating points
print(random.rand())
print(random.rand(3))
print(random.rand(3,2))

0.8468109768788897
[0.86967067 0.46527643 0.01906436]
[[0.16633491 0.57223746]
 [0.33484978 0.34895573]
 [0.97630555 0.89232832]]


In [5]:
a= random.randint(100,size=(3,2))
a

array([49, 74, 11])

In [9]:
random.choice(a)     #single element will be selected

49

In [11]:
random.choice([1,2,3,4,5],size=(4,4))    #for generating an array with the given shape and elements from given list

array([[4, 1, 2, 1],
       [5, 4, 2, 5],
       [3, 3, 4, 1],
       [2, 4, 4, 3]])

###PANDAS
#1. DATA MANIPULATION , ANALYSIS , CLEANING
#2. TABULAR DATA,UNLABELLED DATA

In [ ]:
#creating a dataframe
#1.using 2 dictionaries

In [7]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}               #nan means not a number
dict2={'a':5,'b':6,'c':7,'d':8,'e':9}
data={"First":dict1,"Second":dict2}             #by default values are in float
df=pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [8]:
#2.using simple dictionary--->to data frame
d1={"name":["meghana","ravmyah","sahithi"],"address":["hyd","ngkl","spt"]}
df1=pd.DataFrame(d1)
df1

name address
0  meghana     hyd
1  ravmyah    ngkl
2  sahithi     spt

In [9]:
#using series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([12.23,23.34,45.3,45.5,67.4,67.78,34.45,23.34,67.4,23])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"column1":s1,"column2":s2,"column3":s3}
df3=pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

## selecting the data from data frame:
1.loc
2.iloc  #index based

In [10]:
df3["column2"]

0    12.23
1    23.34
2    45.30
3    45.50
4    67.40
5    67.78
6    34.45
7    23.34
8    67.40
9    23.00
Name: column2, dtype: float64

In [11]:
#extracting multiple column data from datasets
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    45.30       c
3    45.50       d
4    67.40       e
5    67.78       f
6    34.45       g
7    23.34       h
8    67.40       i
9    23.00       j

In [12]:
#single column
df3.loc[:,"column1"]                 #loc[row index,column]   if row index is ":"-->all values

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [15]:
#extracting multiple column values
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.50
4        5    67.40
5        6    67.78

In [16]:
#iloc
df3.iloc[:,0]             #0th column values

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [17]:
df3.iloc[0:4,0:1] 

column1
0        1
1        2
2        3
3        4

###retrieving the information from the data frame

In [18]:
df3.info()                 #gives information about your data frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
column1    10 non-null int64
column2    10 non-null float64
column3    10 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 320.0+ bytes


In [19]:
df3.shape                #gives no. of rows and columns of your data frame

(10, 3)

In [21]:
df3.columns               #gives all the columns of your data frame

Index(['column1', 'column2', 'column3'], dtype='object')

In [22]:
df3.index               

RangeIndex(start=0, stop=10, step=1)

##viewing data from data frame  head(),tail(),sample()

In [24]:
df3.head(3)        #returned first 3 rows           #returns the first 5 rows of data frame by default unless mentioned

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c

In [27]:
df3.tail(2)      #returned last 2 rows  #returns last 5 rows by default

column1  column2 column3
8        9     67.4       i
9       10     23.0       j

In [28]:
df3.sample(2)      #returns random rows

column1  column2 column3
4        5     67.4       e
8        9     67.4       i

In [29]:
df3.describe()          #counts mean,min,max,std,etc.. does not give anything for column3 as it has alphabets

column1    column2
count  10.00000  10.000000
mean    5.50000  40.974000
std     3.02765  20.997852
min     1.00000  12.230000
25%     3.25000  23.340000
50%     5.50000  39.875000
75%     7.75000  61.925000
max    10.00000  67.780000

In [30]:
#renaming the column header
df3=df3.rename(columns={"column1":"First","column2":"Second","column3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.50     d
4      5   67.40     e
5      6   67.78     f
6      7   34.45     g
7      8   23.34     h
8      9   67.40     i
9     10   23.00     j